# -*- coding: utf-8 -*-
"""Machine_Learning_Final_project (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16_JtSEdXuSS0CnxUjvtgci7WUFU1Fsd7

# Title: Unveiling the Cosmos: Classifying Stars, Galaxies and Quasars.
A Machine Learning Journey through Astronomical Objects.

Team Members:

*  Hariharan Chitra Muthukumar - 87523108
*  Parampreet Kaur Sukhvinder Singh  Bhela- 81130840

The Cosmic Challenge(Problem Statement).

So what are we actually trying to solve?
Have you ever imagine looking up in the sky at night and wondering like, its full of uncountable lights! But our question is like what actually are they?
Are they twinking "Stars" like our sun?
Are they a huge collection of Stars, dust and gases called "Galaxies"?
or
Are they bright, distant objects powered by super massive black holes, known as "Quasars"?

Our big challenge in this project is to build a computer program which is obviously called as Machine Learning models that can automatically identify the different celestial bodies based on their lights and other properties. This can help astronomers to understand our universe better and faster!

To teach our programs we actually need examples which is called as Data in programing language.
So here we are using the Data called as ***star_classification.csv***
Its a huge collection of photos and measurements taken by powerful telescope like the Sloan Digital Sky Survey.


Each row in our dataset is like a detailed description of one object in the sky.

It tells us things like:
* **How bright it is** in different colors of light (like u, g, r, i, z - imagine them as different colored glasses the telescope is  wearing!).
* **Where it is** in the sky (alpha, delta).
* And most importantly, what **class** it actually is: a GALAXY, a STAR, or a QSO.


---



Our role is to enable the computer to use existing descriptions to accurately identify celestial objects it encounters for the first time.


So here we start working by loading our dataset.
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/drive/MyDrive/dataset/star_classification.csv")
df.head()

"""Basic information about our dataset like checking its size and columns ad a quick lookout for the different type of sky objects in our dataset."""

df.info()

"""Cleaning and prepairing:
Checking for the missing values or outliers.
"""

df.isnull().sum(0)

"""Looking at our data through statistical approach."""

df.describe()

print(df['class'].value_counts())

"""Distribution of the objects with the help of bar chart.



"""

plt.figure(figsize=(8, 6))
sns.countplot(x='class', data=df)
plt.title('Distribution of Celestial Object Classes')
plt.xlabel('Class')
plt.ylabel('Count')
plt.show()

"""Splitting the data for training(80%) and test(20%) sets."""

from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split ,GridSearchCV ,RandomizedSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix


for col in ['u', 'g', 'z']:
    df[col] = df[col].replace(-9999.0, np.nan)
    df[col] = df[col].fillna(df[col].median())

le = LabelEncoder()
df['class_encoded'] = le.fit_transform(df['class'])
class_names = le.classes_
columns_to_drop = [
    'obj_ID', 'rerun_ID', 'class',
    'run_ID', 'cam_col', 'field_ID', 'spec_obj_ID', 'plate', 'MJD', 'fiber_ID'
]
df_cleaned = df.drop(columns=columns_to_drop, errors='ignore')

X = df_cleaned.drop('class_encoded', axis=1)
y = df_cleaned['class_encoded']
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42, stratify=y)

"""Baseline model: Logistic Regression"""

baseline_model = LogisticRegression(solver='liblinear', random_state=42, max_iter=200)
baseline_model.fit(X_train, y_train)

y_pred = baseline_model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")

print("\nClassification Report:")
print(classification_report(y_test, y_pred, target_names=class_names))

"""Confusion matrix: To give a visual representation that for how many times logistic regression model have accurately predicted the class of the objects."""

conf_matrix = confusion_matrix(y_test, y_pred)
print("\nConfusion Matrix:")

plt.figure(figsize=(6, 4))
sns.heatmap(conf_matrix, annot=True, fmt='d', cmap='Blues', xticklabels=class_names, yticklabels=class_names)
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title('Confusion Matrix for Baseline Logistic Regression')
plt.show()

"""Here we are working with three more different models:

*  Random Forest Classifier.
*  Gradient Boosting Classifier.
*  SVC Classifier

For each we are working with twoo methods:

*   Grid Search.
*   Randomized Search.






"""

from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC

print("\n--- Automated Model Adaptation (Analogy to LLM Fine-tuning) ---")

models_to_adapt = {
    "RandomForest_Classifier": {
        "estimator": RandomForestClassifier(random_state=42),
        "adaptation_settings_grid": {
            'n_estimators': [100],
            'max_depth': [20],
        },
        "adaptation_method": "GridSearch"
    },
    "GradientBoosting_Classifier": {
        "estimator": GradientBoostingClassifier(random_state=42),
        "adaptation_settings_grid": {
            'n_estimators': [100],
            'learning_rate': [0.1],
        },
        "adaptation_method": "GridSearch"
    },
    "SVC_Classifier": {
        "estimator": SVC(random_state=42),
        "adaptation_settings_grid": {
            'C': [1],
            'gamma': ['scale'],
        },
        "adaptation_method": "RandomizedSearch"
    }
}

adapted_results = {}
unadapted_results_summary = {}

for model_name, config in models_to_adapt.items():
    print(f"\n--- Adapting {model_name} ---")

    general_model_estimator = config["estimator"]
    adaptation_settings_grid = config["adaptation_settings_grid"]
    adaptation_method = config["adaptation_method"]

    # Evaluate UN-ADAPTED model
    unadapted_model = general_model_estimator
    unadapted_model.fit(X_train, y_train)
    y_pred_unadapted = unadapted_model.predict(X_test)
    unadapted_results_summary[model_name] = accuracy_score(y_test, y_pred_unadapted)
    print(f"Accuracy (Un-adapted): {unadapted_results_summary[model_name]:.4f}")

    # Perform Automated Adaptation
    if adaptation_method == "GridSearch":
        adaptation_search = GridSearchCV(estimator=general_model_estimator,param_grid=adaptation_settings_grid,cv=2, scoring='accuracy', n_jobs=-1, verbose=0)
    else:
        adaptation_search = RandomizedSearchCV(estimator=general_model_estimator, param_distributions=adaptation_settings_grid,n_iter=1, cv=2, scoring='accuracy', n_jobs=-1, verbose=0, random_state=42)

    adaptation_search.fit(X_train, y_train)
    best_adaptation_params = adaptation_search.best_params_
    print(f"Best settings found: {best_adaptation_params}")

    # Train and evaluate ADAPTED model
    final_adapted_model = general_model_estimator.__class__(**best_adaptation_params, random_state=42)
    final_adapted_model.fit(X_train, y_train)
    y_pred_adapted = final_adapted_model.predict(X_test)
    accuracy_adapted = accuracy_score(y_test, y_pred_adapted)

    adapted_results[model_name] = {
        "accuracy_test": accuracy_adapted,
        "best_params": best_adaptation_params
    }

    print(f"Accuracy (Adapted): {accuracy_adapted:.4f}")
    print("Classification Report (Adapted):")
    print(classification_report(y_test, y_pred_adapted, target_names=class_names))
    print("Confusion Matrix (Adapted):")
    print(confusion_matrix(y_test, y_pred_adapted))

"""Evaluation Criterion:

1] Accuracy Score

2] Classification report

3] Confusion Matrix
"""